Repository Team-EverFlow/Koreasy-Dev, pull requests merged in 2023-08, with the labels that each got.

#9 [Feat] Add color and font set
  package-lock.json
  package.json
  src/styles/colors.scss
  src/styles/textStyles.scss
Labels: enhancement

#18 [Feat] #17 - 구글 로그인 구현
  .gitignore
  package-lock.json
  package.json
  src/firebase/api/authAPI.js
  src/firebase/functions/util.js
  src/firebase/root.js
  src/firebase/type/const.js
  src/firebase/type/typedef.js
Labels: enhancement

#16 [Feat] Login Page view
  src/assets/google.png
  src/pages/login.jsx
  src/styles/pages/login.scss
Labels: enhancement

#20 [Feat] unification assets and styles
  src/assets/images/Profile_Red.svg
  src/assets/images/google.png
  src/components/dump.js
  src/pages/login.jsx
  src/styles/login.scss
  src/styles/variables.scss
  src/styles/variables/colors.scss
  src/styles/variables/textStyles.scss
Labels: enhancement

#23 [Fix] #22 - Update GoogleAuth jsdoc
  src/firebase/api/authAPI.js
Labels: bug

#24 [Feat] #21 - Add Set user and Get user
  src/firebase/api/userAPI.js
  src/firebase/type/const.js
Labels: enhancement

#26 Feature/10 central components
  .vscode/settings.json
  public/index.html
  src/Router.js
  src/actions/index.js
  src/assets/images/ProfileRed.svg
  src/assets/images/dump.json
  src/components/Chevrion.jsx
  src/components/Divider.jsx
  src/components/Divider.scss
  src/components/Footer.jsx
  src/components/Footer.scss
  src/components/Header.jsx
  src/components/Header.scss
  src/components/NavigationBar.jsx
  src/components/NavigationBar.scss
  src/components/PageTitle.jsx
  src/components/PageTitle.scss
  src/components/ProfileEdit.css
  src/components/dump.js
  src/config.js
  src/containers/reduxTest.js
  src/reducers/index.js
  src/reducers/reducer_setting.js
  src/store.js
  src/styles/variables/colors.scss
Labels: enhancement

#30 [Feat] 확정 컬러 셋 등록
  src/Router.js
  src/components/Chevrion.jsx
  src/components/Divider.scss
  src/components/Footer.scss
  src/components/Header.scss
  src/components/NavigationBar.scss
  src/components/PageTitle.scss
  src/pages/login.jsx
  src/styles/login.scss
  src/styles/variables/colors.scss
Labels: enhancement

#33 [Bugfix] Can't send argument to central component
  src/components/Chevrion.jsx
  src/components/Header.jsx
  src/components/NavigationBar.jsx
  src/components/PageTitle.jsx
Labels: bug

#43 WordTestList View 구현
  package-lock.json
  package.json
  src/Router.js
  src/pages/wordTest/DumpData.js
  src/pages/wordTest/GoToTest.jsx
  src/pages/wordTest/LearnWords.jsx
  src/pages/wordTest/TestPageGoToTest.jsx
  src/pages/wordTest/TestPageLearnWords.jsx
  src/pages/wordTest/WordTestList.jsx
  src/pages/wordTest/WordTestTitle.jsx
  src/styles/GoToTest.scss
  src/styles/LearnWords.scss
  src/styles/WordTestList.scss
  src/styles/WordTestTitle.scss
Labels: enhancement

#41 [Fix] #40 - Fixed className duplication
  src/pages/mainView/LearnTodayWord.jsx
  src/pages/mainView/StartThumbnail.jsx
  src/styles/LearnTodayWord.scss
  src/styles/StartThumbnail.scss
Labels: bug

#54 [Feat] Set profile view and my badge view interaction
  src/Router.js
  src/components/Header.jsx
  src/components/NavigationBar.jsx
  src/components/NavigationBar.scss
  src/pages/MyBadges.jsx
  src/pages/MyBadgesSetting.jsx
  src/pages/Profile.jsx
  src/styles/MyBadge.scss
Labels: enhancement

#52 [Feat] bookmark add remove
  src/firebase/api/userAPI.js
  src/firebase/api/wordAPI.js
Labels: enhancement

#63 [Feat] Create custom toast component
  src/assets/images/warning.svg
  src/components/Toast.jsx
  src/components/Toast.scss
  src/components/ToastGenerator.jsx
  src/styles/variables/textStyles.scss
Labels: enhancement

#59 [Feat] - #51 register function
  src/firebase/api/userAPI.js
Labels: enhancement

#62 [Feat] - #60 Add GetWordTestList and GetTestDataList
  src/firebase/api/QuizApi.js
  src/firebase/type/const.js
  src/firebase/type/typedef.js
Labels: enhancement

#64 [Feat] OAuth2 button feature
  package-lock.json
  src/Router.js
  src/pages/Login.jsx
  src/pages/login.jsx
  src/styles/Login.scss
Labels: bug, enhancement

#68 [Feat] recovering login oauth2 feature
  src/Router.js
  src/pages/Login.jsx
  src/pages/login.jsx
  src/pages/wordweekPage/BookmarkIcon.jsx
  src/styles/Login.scss
Labels: enhancement

#71 [Feat] profile view interaction from backend
  src/pages/Profile.jsx
  src/styles/Profile.scss
  src/types/typedef.js
Labels: bug, enhancement

#73 [Feat] mybadge setting view interaction
  src/components/Badge.jsx
  src/components/BadgeGroup.jsx
  src/pages/MyBadges.jsx
  src/pages/MyBadgesSetting.jsx
  src/pages/dumpBadge.js
  src/types/typedef.js
Labels: enhancement

#77 [Feat] - #74 Add comment function
  src/firebase/api/wordAPI.js
  src/firebase/type/const.js
  src/firebase/type/typedef.js
Labels: enhancement

#80 Feature/76 feat main view
  src/components/Footer.jsx
  src/pages/mainView/MainPage.jsx
  src/styles/MainPage.scss
Labels: enhancement

#79 [Feat] - #78 Add testscore
  src/firebase/api/QuizApi.js
  src/firebase/api/userAPI.js
  src/firebase/type/typedef.js
Labels: enhancement

#87 [Feat] - #86 Add login-state-persistence
  src/firebase/api/authAPI.js
Labels: enhancement

#88 [Feat] - #82 Add AddRepBadge
  src/firebase/api/BadgeApi.js
Labels: enhancement

#90 Feature/84 word type update
  src/firebase/api/wordAPI.js
  src/firebase/type/typedef.js
Labels: enhancement

#92 [Fix] - #91 Fix login persistence
  src/firebase/api/authAPI.js
  src/firebase/root.js
Labels: bug

#100 Feature/85 add header function
  package.json
  src/Router.js
  src/components/Badge.jsx
  src/components/BadgeGroup.jsx
  src/components/BadgeNotification.jsx
  src/components/Divider.jsx
  src/components/ExampleSentence.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/NavigationBar.jsx
  src/components/PageTitle.jsx
  src/components/ProfileButton.jsx
  src/components/Toast.jsx
  src/containers/reduxTest.js
  src/index.js
  src/pages/Profile.jsx
  src/pages/mybadge/MyBadges.jsx
  src/pages/mybadge/MyBadgesSetting.jsx
  src/pages/mybadge/dumpBadge.js
  src/pages/todayWordPage/TodayWordCard.jsx
  src/reducers/index.js
  src/reducers/reducer_setting.js
  src/styles/common.scss
  src/styles/components/Badge.scss
  src/styles/components/BadgeGroup.scss
  src/styles/components/BadgeNotification.scss
  src/styles/components/Divider.scss
  src/styles/components/ExampleSentence.scss
  src/styles/components/Footer.scss
  src/styles/components/Header.scss
  src/styles/components/NavigationBar.scss
  src/styles/components/PageTitle.scss
  src/styles/components/ProfileButton.scss
  src/styles/components/Toast.scss
  src/styles/reset.scss
Labels: enhancement

#94 [Feat] - 83 date type return
  src/firebase/api/wordAPI.js
  src/firebase/type/typedef.js
Labels: enhancement

#95 [Fix] - #93 Modify GetCurrentUserInformation function
  src/firebase/api/userAPI.js
Labels: bug

#98 [Feat] logout
  src/firebase/api/userAPI.js
Labels: enhancement

#99 [Feat] - todayword function
  src/firebase/api/wordAPI.js
Labels: enhancement

#103 Feature/35 today word view
  package-lock.json
  package.json
  src/components/ExampleSentence.jsx
  src/components/WordCardText.jsx
  src/components/WordCardText.scss
  src/dummyData/todayWordDump.js
  src/dummyData/wordCommentDump.js
  src/pages/mainView/MainPage.jsx
  src/pages/todayWordPage/TodayCheckComponent.jsx
  src/pages/todayWordPage/TodayWordCard.jsx
  src/pages/todayWordPage/TodayWordTest.jsx
  src/pages/todayWordPage/TodayWordView.jsx
  src/pages/wordCommunityPage/AddComment.jsx
  src/pages/wordCommunityPage/Comment.jsx
  src/pages/wordCommunityPage/WordCommunityView.jsx
  src/pages/wordCommunityPage/wordData.js
  src/styles/todayWordPage/TodayCheckComponent.scss
  src/styles/todayWordPage/TodayWordCard.scss
  src/styles/todayWordPage/TodayWordView.scss
  src/styles/wordCommunityPage/AddComment.scss
  src/styles/wordCommunityPage/Comment.scss
  src/styles/wordCommunityPage/WordCommunityView.scss
  src/utils/TodayCvtEN.jsx
Labels: enhancement

#112 [Feat] - #110 Add delete user
  src/firebase/api/userAPI.js
Labels: enhancement

#113 [Feat] comment react
  src/firebase/api/wordAPI.js
  src/firebase/type/typedef.js
Labels: enhancement

#121 [Feat] - Add addedTime
  src/firebase/api/BadgeApi.js
  src/firebase/root.js
  src/firebase/type/typedef.js
Labels: enhancement

#119 [Fix] - Fix user delete
  src/firebase/api/BadgeApi.js
  src/firebase/api/userAPI.js
Labels: bug

#125 [Fix] - WordTestView structure
  src/firebase/api/QuizApi.js
  src/firebase/type/typedef.js
Labels: bug

#122 [Fix] - Delete Initialize myBadge
  src/firebase/api/userAPI.js
Labels: enhancement

#123 [Feat] Change badge object structure
  src/assets/badges/attend_badge/attend_badge_lv1.svg
  src/assets/badges/attend_badge/attend_badge_lv1_disable.svg
  src/assets/badges/attend_badge/attend_badge_lv2.svg
  src/assets/badges/attend_badge/attend_badge_lv2_disable.svg
  src/assets/badges/attend_badge/attend_badge_lv3.svg
  src/assets/badges/attend_badge/attend_badge_lv3_disable.svg
  src/assets/badges/attend_badge/attend_badge_lv4.svg
  src/assets/badges/attend_badge/attend_badge_lv4_disable.svg
  src/assets/badges/attend_badge/attend_badge_lv5.svg
  src/assets/badges/attend_badge/attend_badge_lv5_disable.svg
  src/assets/badges/comment_badge/comment_badge_lv1.svg
  src/assets/badges/comment_badge/comment_badge_lv1_disable.svg
  src/assets/badges/comment_badge/comment_badge_lv2.svg
  src/assets/badges/comment_badge/comment_badge_lv2_disable.svg
  src/assets/badges/comment_badge/comment_badge_lv3.svg
  src/assets/badges/comment_badge/comment_badge_lv3_disable.svg
  src/assets/badges/comment_badge/comment_badge_lv4.svg
  src/assets/badges/comment_badge/comment_badge_lv4_disable.svg
  src/assets/badges/comment_badge/comment_badge_lv5.svg
  src/assets/badges/comment_badge/comment_badge_lv5_disable.svg
  src/assets/badges/special_badge/unknown_badge.svg
  src/assets/badges/test_badge/test_badge_lv1.svg
  src/assets/badges/test_badge/test_badge_lv1_disable.svg
  src/assets/badges/test_badge/test_badge_lv2.svg
  src/assets/badges/test_badge/test_badge_lv2_disable.svg
  src/assets/badges/test_badge/test_badge_lv3.svg
  src/assets/badges/test_badge/test_badge_lv3_disable.svg
  src/assets/badges/test_badge/test_badge_lv4.svg
  src/assets/badges/test_badge/test_badge_lv4_disable.svg
  src/assets/badges/test_badge/test_badge_lv5.svg
  src/assets/badges/test_badge/test_badge_lv5_disable.svg
  src/components/Badge.jsx
  src/components/BadgeGroup.jsx
  src/firebase/api/BadgeApi.js
  src/pages/Login.jsx
  src/pages/Profile.jsx
  src/pages/mybadge/MyBadges.jsx
  src/pages/mybadge/MyBadgesSetting.jsx
  src/pages/mybadge/badgeList.js
  src/pages/mybadge/dumpBadge.js
  src/pages/mybadge/unknownBadge.js
  src/pages/mybadge/updateBadgeObject.js
  src/styles/MyBadge.scss
  src/styles/components/Badge.scss
  src/styles/components/BadgeGroup.scss
  src/types/typedef.js
Labels: bug, enhancement

#128 [Feat] change wordtestlist struction and sorting list
  src/Router.js
  src/pages/mybadge/updateBadgeObject.js
  src/pages/wordtestListPage/WordTestCell.jsx
  src/pages/wordtestListPage/WordTestList.jsx
  src/utils/ordinalSuffix.js
Labels: bug

#132 [Fix] - #131 Fix get word data
  src/firebase/api/wordAPI.js
Labels: bug

#133 [Feat] wordbook interaction from backend
  package-lock.json
  src/firebase/api/wordAPI.js
  src/pages/Profile.jsx
  src/pages/myBookMarkPage/MyBookMark.jsx
  src/pages/wordbookPage/WordBook.jsx
  src/pages/wordweekPage/WordWeek.jsx
Labels: enhancement

#130 [Fix] - #129 Fix get word
  src/firebase/api/wordAPI.js
Labels: enhancement

#135 [Feat] badge notification interaction
  src/components/Badge.jsx
  src/components/BadgeNotification.jsx
  src/components/BadgeNotificationGenerator.jsx
  src/firebase/functions/Events.js
  src/firebase/root.js
  src/firebase/type/typedef.js
  src/pages/wordtestSheetPage/WordTestSheet.jsx
  src/styles/components/BadgeNotification.scss
  src/types/const.js
  src/utils/badgeImage.js
Labels: enhancement

#139 [Feat] - #138 Update Test badge condition
  src/firebase/api/QuizApi.js
  src/firebase/functions/Events.js
Labels: enhancement

#140 [Fix] #111 - Fixed EventListener
  src/firebase/root.js
Labels: bug

#144 Fixbug/141 page qa mule
  public/favicon.ico
  src/Router.js
  src/components/Footer.jsx
  src/pages/Login.jsx
  src/pages/Profile.jsx
  src/pages/mainView/MainPage.jsx
  src/pages/mainView/StartThumbnail.jsx
  src/pages/todayWordPage/TodayWordCard.jsx
  src/pages/wordbookPage/WordBook.jsx
  src/pages/wordtestListPage/LearnWords.jsx
  src/pages/wordtestSheetPage/WordTestResult.jsx
Labels: bug, enhancement

#143 [Fix] - #142 Fix comment reaction
  src/pages/wordCommunityPage/Comment.jsx
Labels: bug

#146 [Docs] #145 - Update README.md
  README.md
Labels: documentation
